### PR TITLE
Update helm charts based on local development experience

### PR DESCRIPTION
**Pull request by allenporter**
**Description of the change**

Update the docs based on learnings from following them:
- Rename the _ to a - since that matches the style in the existing repo.
- Update the url for the library chart.

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

### CODE REVIEW

**Comment by allenporter** [comment]
Also, would it make sense for me to update the tasks to create the chart in `incubator`? (or `stable`)

**Comment by bjw-s** [comment]
> Also, would it make sense for me to update the tasks to create the chart in `incubator`? (or `stable`)

Good question... I've thought about this as wel during the incubator/stable split. I'm not sure where new charts should go by default. Incubator seems like the way to go, but then the version number needs to be something like 0.0.1 initially.

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
> Also, would it make sense for me to update the tasks to create the chart in `incubator`? (or `stable`)

You don't have to, I'm thinking incubator will not be used often enough. The usecase I imagined for incubator was too work on any chart that seemed complicated, isn't ready for primetime, or just something we want to test. I don't think we want to be promoting charts from incubator to stable a lot. If using the common library there's likely going to be less mistakes or issues in the chart if it's simple enough.

**Comment by allenporter** [comment]
Ok so the related thing is:

-  The tasks creating a chart in the root for which you have to move to stable/. Easy enough, took a few seconds to move.
- The lint commands need something like `CHART=stable/chart-name` but they still work. (I suspect that doesn't work for create since it uses the name in the chart forks.)

My task-fu isn't super strong but I was imagining a default variable like `FOO=stable` would work to make this transparent.

**Pull request merged**
