### PR TITLE
Addition of markdownlint-cli

### PR DESCRIPTION
**Pull request by nicholaswilde**
**Description of the change**

- Implements mardkownlint-cli into task, pre-commit, and lint gh action.
- Lints all of markdown files.

**Benefits**

Makes markdown files more uniform

**Possible drawbacks**

Some formatting of pages may have been broken.

**Applicable issues**

N/A

**Additional information**

N/A

### CODE REVIEW

**Comment by bjw-s** [comment]
That's a pretty neat one! 
I just looked around to see if there were any pre-made Github Actions. I found https://github.com/nosborn/github-action-markdown-cli, but it does seem like abondonware by now, so it may be better to just stick with the current approach?

Also I found this: https://github.com/gaurav-nelson/github-action-markdown-link-check
It may also be worth implementing, that way we can make sure our links are still valid.

**Comment by nicholaswilde** [comment]
> Also I found this: https://github.com/gaurav-nelson/github-action-markdown-link-check
> It may also be worth implementing, that way we can make sure our links are still valid.

I'll take a look.

**Comment by nicholaswilde** [comment]
I'd like to implement `markdown-link-check` in a separate PR if possible.

**Comment by onedr0p** [comment]
That's fine :)

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
